Add Database and Firestore examples
GodotNuts/GodotFirebase pull request #127
Opened 2021-02-15 08:26 UTC by timjrobinson

- Add Realtime Database host game example that creates a game in `/rooms` with a room code, and then listens for updates. 
- Add Firestore host game example that creates a game in `rooms` collection in Firestore, then polls for updates on 1s interval (as there is currently no way to listen for updates with Firestore).

These are examples to demonstrate #126 

Both these examples should be working but aren't since the refactoring today. I'd like to add these so they can be used as test cases to test against when releasing new changes to GodotFirebase. As when using main branch things keep breaking for me.

2021-02-15 08:45 UTC, timjrobinson commented
Ok I fixed the Firestore example not working by fixing the callback, the `get` and `add` signals were reversed. 

You also need to create the collection first or it gives an authentication error, not sure if it's possible to create the initial collection with with this plugin or not.

2021-02-15 10:51 UTC, WolfgangSenff requested changes
Sorry, there's some confusion here. We have separate repositories for our examples/demos. We intentionally aren't including them here. That said, we may be swayable otherwise.

2021-02-15 10:52 UTC, WolfgangSenff commented
Here, for example: https://github.com/GodotNuts/FirebaseDemo-Chat

2021-02-15 11:09 UTC, timjrobinson commented
Is there a way these could be added as automatically run integration tests? I'd like something to check basic flows work after changes.

2021-02-15 12:57 UTC, WolfgangSenff commented
Hm. That's a really good question. I'll look again to see if that's possible, but if it's a true integration test, I can't have that hitting my Firebase instance (which I assume would be needed), and I'm not about to let it hit anyone else's. I wonder if there's a Github Action that allows you to download the Firebase Simulator and run tests against it instead of live.

2021-02-15 13:16 UTC, WolfgangSenff commented
Alright, after talking to the team about this, we think it's worth elevating to its own demo for game-hosting with Firebase. If I create a new repo for what, would you care to join the team and begin working on the demo so it's a bit more fully-fleshed-out? You wouldn't also have to join the team, but you've contributed so much, I think we'd be happy to have you.

2021-02-16 04:24 UTC, timjrobinson commented
I like the idea of a Github Action that can spin up the Firebase Simulator and run it with that. I could do a demo eventually but probably don't have time right now as I'm trying to make a game a week. I'm using this package for puzzop.com games and I stream all development at twitch.tv/puzzop so you can see me struggling with the plugin there :p

2021-02-16 14:47 UTC, WolfgangSenff commented
Geez! If you'd told me ORIGINALLY, I'd have come watched your stream much earlier and offered help. :D That's awesome! Really good to see people using it. Regarding GitHub Actions, it looks like in theory it should be possible, but I have not yet figured out a good way to actually do it. I'm going to see if I can talk to someone from the Firebase team about it directly, as it's probably easier to get info that way than hoping #AskFirebase answers something. :P

2021-02-26 00:04 UTC, WolfgangSenff commented
I'm going to go ahead and close this. You can open an issue if you need us to create a demo project for which you can add this code (I'm happy to do it, just for tracking purposes I'd like to have the issue please).

2021-02-26 00:04 UTC, closed without merging